### ISSUE TITLE
Is currentTime wrong?

### ISSUE THREAD

**Issue by baimurzin** [collab-project/videojs-record#129]
When I call `player.currentTime()` it shows me different time with time on controls bar.
For example, on controls bar when I recording displays `0:02` and when I clicked a button that logs currentTime the button logs `5.434436` 
So, how can I get exact time?

**Comment by thijstriemstra** [comment]
@baimurzin during recording you can use `player.recorder.streamDuration` to get the current length of the recorded stream. I will add a `player.recorder.getDuration()` method and document it that does the same.

It looks like a method to get the current time of a recorded stream during playback is missing, or not working, because `player.currentTime()` always returns 0 here. I'll add a player.recorder.getCurrentTime()` that does the same.

**Comment by thijstriemstra** [comment]
When I print the streamDuration after an audio-only recording it displays 8.09 for example, but the player shows 9.91. ffprobe shows the correct duration is 9.91 so there's also a bug somewhere.

```
  Duration: 00:00:09.91, start: 0.000000, bitrate: 52 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, mono, fltp
    Metadata:
      ENCODER         : Mozilla51.0.1
```

**Comment by thijstriemstra** [comment]
Added `getDuration` and `getCurrentTime`. Tested with with audio-only and that seems to work fine (you'll need videojs-wavesurfer 1.3.1 or newer). Let me know if this works for you @baimurzin.

**Comment by baimurzin** [comment]
Thanks for response @thijstriemstra .
I had already did almose save thing, clone repo and add event in your onCountDown method that returns the current time also added getter for current time.
So for that reason I need  "videojs-wavesurfer"?

**Comment by thijstriemstra** [comment]
@baimurzin you only need videojs-wavesurfer (1.3.1 or newer) if you're also recording audio-only.
