### ISSUE TITLE
Question : Does this library support video capture cards or only webcams?

### ISSUE THREAD

**Issue by SevenSinS02** [collab-project/videojs-record#284]
I would like to know if this library can help with media that is captured using a video capture card. Like this one for example [video capture card](https://www.datapath.co.uk/datapath-products/video-capture-cards/vision-range/visionrgb-e2s)

**Comment by thijstriemstra** [comment]
If the card shows up in the browser as video capture device, then yes it works. You can test it easily by running one of videojs-record video examples.

This sounds promising: "any application compatible with Windows® Direct-Show technology can use the VisionRGB-E2S video capture card due to its built in WDM support."

**Comment by SevenSinS02** [comment]
@thijstriemstra I don't have the capture card yet. So I wanted to be sure that I could use this library when I do have hold of it. 
Thanks for the reply though.
