### ISSUE TITLE
How to set additional parameters for plugins

### ISSUE THREAD

**Issue by akalmykov** [collab-project/videojs-record#383]
Hi All,

I am using [opus-recorder](https://github.com/chris-rudmin/opus-recorder) as a recorder plugin. I need to configure some options of the Opus OGG encoder, e.g. I need to set **originalSampleRateOverride** parameter of opus-recorder. 

Is there any nice way to configure opus-recorder while initializing videojs/videojs-record objects or afterwards? Or I have to patch something in videojs.record.opus-recorder.js?

Thanks in advance!

**Comment by thijstriemstra** [comment]
@akalmykov good question. Because every plugin uses a different 3rd-party library, there can be many different options used by some plugins, and totally irrelevant to other plugins. I guess the time has come to simply use a couple of 'base' options that are common to all (audio) plugins and put any addtional/optional settings in a object that get's merged into the config/base options and that is passed to the 3rd-party library.

Identifying all these options for the various plugins would be step 1. Then making a general set of options, and putting the rest into an additional config object would be step 2.

So something like:

```javascript
record: {
            audio: true,
            video: false,
            maxLength: 20,
            debug: true,
            audioEngine: 'opus-recorder',
            audioSampleRate: 48000,
            audioChannels: 2,
            audioWorkerURL: '../../node_modules/opus-recorder/dist/encoderWorker.min.js',
            audioOptionalConfig: {
                originalSampleRateOverride: 'myValue'
            }
        }
```

I don't like the `audioOptionalConfig` name though. Thoughts?

**Comment by thijstriemstra** [comment]
@akalmykov you'll be able to set additional options using the `pluginLibraryOptions` in upcoming v3.8.0 release.

For example:

```javascript
record: {
            audio: true,
            video: false,
            maxLength: 20,
            debug: true,
            audioEngine: 'opus-recorder',
            audioSampleRate: 48000,
            audioChannels: 2,
            audioWorkerURL: '../../node_modules/opus-recorder/dist/encoderWorker.min.js',
            // use the pluginLibraryOptions option to specify optional settings for the
            // opus-recorder library
            pluginLibraryOptions: {
                monitorGain: 0.4,
                originalSampleRateOverride: 16000
            }
        }
```
