### ISSUE TITLE
Enable voice for chrome when recording both audio/video

### ISSUE THREAD

**Issue by durimrexhaj** [collab-project/videojs-record#4]
In chrome voice doesnt work. How can i fix it

**Comment by thijstriemstra** [comment]
hi @durimrexhaj, can you please explain in detail why and what isn't working on what version/operating system?

**Comment by durimrexhaj** [comment]
hiw @thijstriemstra I'm using windows and chrome Version 43.0.2357.130. Recorder doesn't get the voice. When i play video i can't here voice in chrome.

**Comment by thijstriemstra** [comment]
@durimrexhaj I haven't tested it on windows chrome, so I'll give it a try and see what's going on.

**Comment by durimrexhaj** [comment]
hi @thijstriemstra I have tested RecordRTC script and it worked well for me and i saw the videojs-record uses RecordRTC but I don't know why is not working with this plugin. Thanks a lot

**Comment by thijstriemstra** [comment]
@durimrexhaj, what example did you use? Or what code are you using?

**Comment by pbojinov** [comment]
I noticed the same issue on `Chrome Version 43.0.2357.130 (64-bit)` for `OSX 10.10.3` using the `examples/audio-video.html` provided.

Here's the `audo-video.html` file hosted as is for testing purposes: http://pbojinov.github.io/videojs-record/examples/audio-video.html

**Comment by thijstriemstra** [comment]
I've also tested the examples and noticed the same on windows, linux and osx Chrome browsers. As noted in the README:

```
Note that recording both audio and video in a single WebM file is currently only supported in Mozilla Firefox >= 29. On other browsers the resulting file only contains video data.
```

This is a limitation of Chrome because it hasn't implemented MediaRecorder yet, and Firefox has. What RecordRTC.js does is record, stop stream, make audio data blob available, then make video data blob available. In Firefox it makes a single audio/video blob available after recording.

Now, I noticed that this line https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L441 causes only video-data to be made available, the audio blob is ignored. In a perfect world Chrome would stich the audio and video together in a webm blob, just like Firefox can.

So now, I guess it would be possible to trigger 2 'finishRecord' events, one for audio and one for video, but this would only be necessary in Chrome. Any suggestions?

**Comment by thijstriemstra** [comment]
I've commited a fix for Chrome that makes both audio and video blobs available when the `finishRecord` event fires.

![capture](https://cloud.githubusercontent.com/assets/305679/8603215/2544e400-2677-11e5-9a57-5ca7efb9bdac.PNG)

But during playback it will still only display the video stream and ignore the audio stream (because they're separate objects). I guess syncing the playback of the audio using WebAudio should be possible in that case.

**Comment by thijstriemstra** [comment]
I decided to add an extra `audio` element for chrome when recording audio and video that plays the recorded audio stream in sync with the video element.

Closing this ticket, please open a new one if there's still an issue.

**Comment by pbojinov** [comment]
:+1:

**Comment by v3ss0n** [comment]
What is the format audio and videos are recorded with AUDIO_VIDEO flag? Is that Webm or WAV??

**Comment by thijstriemstra** [comment]
Try it, document it and open a pull request please.
